name: The Elation Music
favicon: null
layout_spectrum: 0.77176
typography_spectrum: 0.4736099436413497
title: The Elation Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1e2329'
    - '#5b6974'
    - '#8499aa'
    - '#6339fd'
  brandStrength: 1
  lightness: 0.7677272765431553
  saturation: 0.9661998490337282
  rhythmicContrast: 0.5542251085862517
purpose: []
