name: The Elation Music
favicon: null
layout_spectrum: 0.32109
typography_spectrum: 0.4736099436413497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0.7677272765431553
  saturation: 0.9661998490337282
  rhythmicContrast: 0.5542251085862517
purpose: []
